server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jarivera94/microservices-spring-boot/tree/02-CONFIG-SERVER
          searchPaths: config-data
