server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jarivera94/microservices-spring-boot.git
          username: ${GITHUB_USER_NAME}
          password: ${GITHUB_PASSWORD}
          search-paths: config-data
  security:
    user:
      name: root
      password: s3cr3t
